spring:
  application:
    name: catalog-service
  datasource:
    url: ${CATALOG_DB_URL:jdbc:postgresql://localhost:5432/thartheeb_catalog}
    username: ${CATALOG_DB_USERNAME:postgres}
    password: ${CATALOG_DB_PASSWORD:admin123}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_JWK_SET_URI:http://localhost:8081/.well-known/jwks.json}

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
